version: "3.8"

services:
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=admin|shh_it_is_a_secret!
      - ADDRESS=ftp.elemento.marketplace
    volumes: 
      - data:/home
    networks:
      - net

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8081:8081"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - net
    depends_on:
      - db

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      - ./docker/homepage/config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - net

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - net

  crontab-ui:
    container_name: crontab-ui
    build: .
    image: alseambusher/crontab-ui
    network_mode: bridge
    ports:
      - "8000:8000"

  traefik:
    container_name: traefik
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

  whoami:
    container_name: whoami
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=yourdomain.url
      - VALIDATION=http
      - SUBDOMAINS=www,
      - CERTPROVIDER=
      - DNSPLUGIN=cloudflare
      - PROPAGATION=
      - EMAIL=
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=
      - STAGING=false
    volumes:
      - config:/config
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - net

volumes:
  cache:
    driver: local
  data:
    driver: local
  config:
    driver: local

networks:
  net:
    driver: bridge