version: "3.8"

services:
  ftp-server:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009" # for passive mode
    volumes:
      - "./ftp/data:/home/admin/"
      - "./ftp/passwd:/etc/pure-ftpd/passwd"
    # uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
    #      - "/folder_on_disk/ssl:/etc/ssl/private/"
    # or ssl/tls with Let's Encrypt (cert and key as two files)
    #      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
    #      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: admin
      FTP_USER_PASS: change_me
      FTP_USER_HOME: /home/admin
    # also for ssl/tls:
    #      ADDED_FLAGS: "--tls=2"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=your_secure_root_password
      - PMA_HOST=mysql_db
      - PMA_PORT=3300
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.web.elemento.cloud`)"
    networks:
      - net
    depends_on:
      - mysql_db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  php:
    image: php:fpm-alpine
    volumes:
      - ./src/public:/var/www/html/
    labels:
        - "traefik.enable=false"
    networks:
      - net

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.nginx.rule=Host(`nginx.web.elemento.cloud`)"
    volumes:
      - ./src/public:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net

  mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: your_secure_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - net

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - ./homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.web.elemento.cloud`)"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"

  # portainer:
  #   image: portainer/portainer-ce:latest
  #   ports:
  #     - "9443:9443"
  #   volumes:
  #     - data:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: unless-stopped
  #   networks:
  #     - net
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.portainer.rule=Host(`portainer.web.elemento.cloud`)"

  crontab-ui:
    image: alseambusher/crontab-ui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crontab.rule=Host(`crontab.web.elemento.cloud`)"
      - "traefik.http.services.crontab.loadbalancer.server.port=8000"
    networks:
      - net

  traefik:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ../src:/var/www/html/
    networks:
      - net

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.web.elemento.cloud`)"
    networks:
      - net

volumes:
  mysql_data:
  data:

networks:
  net:
    external: true
    name: "net"