version: "3.8"

services:
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=admin|shh_it_is_a_secret!
      - ADDRESS=ftp.elemento.marketplace
    volumes: 
      - data:/home
    networks:
      - net

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=your_secure_root_password
      - PMA_HOST=mysql_db
      - PMA_PORT=8080
    networks:
      - net
    depends_on:
      - mariadb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  app:
    container_name: phpfpm_app
    build:
      context: .
      dockerfile: php_fpm/Dockerfile
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
    networks:
      - net

  mariadb:
    image: mariadb:11.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_secure_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - net

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      - ./docker/homepage/config:/app/config 
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - net

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - net

  crontab-ui:
    container_name: crontab-ui
    build: .
    image: alseambusher/crontab-ui
    network_mode: bridge
    ports:
      - "8000:8000"

  traefik:
    container_name: traefik
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

  whoami:
    container_name: whoami
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

  swag:
    container_name: swag
    image: lscr.io/linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=yourdomain.url
      - VALIDATION=http
      - SUBDOMAINS=www,
      - CERTPROVIDER=
      - DNSPLUGIN=cloudflare
      - PROPAGATION=
      - EMAIL=
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=
      - STAGING=false
    volumes:
      - config:/config
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - net

volumes:
  mariadb_data:
    driver: local
  data:
    driver: local
  config:
    driver: local

networks:
  net:
    driver: bridge