version: "3.8"

services:
  ftp-server:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009" # for passive mode
    volumes:
      - /home/admin/dev/elemento-marketplace-web/ftp/data:/home/admin/
      - /home/admin/dev/elemento-marketplace-web/ftp/passwd:/etc/pure-ftpd/passwd
    # uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
    #      - "/folder_on_disk/ssl:/etc/ssl/private/"
    # or ssl/tls with Let's Encrypt (cert and key as two files)
    #      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
    #      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: admin
      FTP_USER_PASS: change_me
      FTP_USER_HOME: /home/admin
    # also for ssl/tls:
    #      ADDED_FLAGS: "--tls=2"
    deploy:
      labels:
        - "traefik.enable=false"
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=your_secure_root_password
      - PMA_HOST=mysql_db
      - PMA_PORT=3307
      - APACHE_PORT=8090
    networks:
      - net
    depends_on:
      - mysql_db
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.web.elemento.cloud`)"
        - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
        - "traefik.http.services.phpmyadmin.loadbalancer.server.port=8090"
        - "traefik.http.routers.phpmyadmin.tls=true"
        - "traefik.http.routers.phpmyadmin.tls.domains[0].main=phpmyadmin.web.elemento.cloud"
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager

  php:
    image: php:fpm-alpine
    volumes:
      - /home/admin/dev/elemento-marketplace-web/src/public:/var/www/html/
    deploy:
      labels:
        - "traefik.enable=false"
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
    networks:
      - net

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    volumes:
      - /home/admin/dev/elemento-marketplace-web/src/public:/var/www/html/
      - /home/admin/dev/elemento-marketplace-web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=Host(`nginx.web.elemento.cloud`)"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.tls=true"
        - "traefik.http.routers.nginx.tls.domains[0].main=nginx.web.elemento.cloud"
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
    networks:
      - net

  mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: your_secure_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
      MYSQL_PORT: 3307
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      labels:
        - "traefik.enable=false"
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - net

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - "/home/admin/dev/elemento-marketplace-web/homepage/config:/app/config"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homepage.rule=Host(`homepage.web.elemento.cloud`)"
        - "traefik.http.services.homepage.loadbalancer.server.port=3000"
        - "traefik.http.routers.homepage.entrypoints=websecure"
        - "traefik.http.routers.homepage.tls=true"
        - "traefik.http.routers.homepage.tls.domains[0].main=homepage.web.elemento.cloud"
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
    networks:
      - net

  crontab-ui:
    image: alseambusher/crontab-ui
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.crontab.rule=Host(`crontab.web.elemento.cloud`)"
        - "traefik.http.services.crontab.loadbalancer.server.port=8000"
        - "traefik.http.routers.crontab.entrypoints=websecure"
        - "traefik.http.routers.crontab.tls=true"
        - "traefik.http.routers.crontab.tls.domains[0].main=crontab.web.elemento.cloud"
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
    networks:
      - net

  ############### MAIL SERVER ###############

  # # Creates self signed tls certificates. Remove if you
  # # use your own.
  # ssl:
  #   image: jeboehm/mailserver-ssl:latest
  #   #env_file: "/home/admin/dev/elemento-marketplace-web/mailserver/mailserver.env"
  #   volumes:
  #     - data-tls:/media/tls:rw
  #   networks:
  #     - net
  #   deploy:
  #     labels:
  #       - "traefik.enable=false"
  #     replicas: 1
  #     placement:
  #       max_replicas_per_node: 1
  #       constraints:
  #         - node.role == manager

  # # Responsible for storing users and their aliases. Remove
  # # if you already have a MySQL server.
  # db:
  #   image: jeboehm/mailserver-db:latest
  #   #env_file: "/home/admin/dev/elemento-marketplace-web/mailserver/mailserver.env"
  #   volumes:
  #     - data-db:/var/lib/mysql
  #   networks:
  #     - net
  #   deploy:
  #     labels:
  #       - "traefik.enable=false"
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.role == manager

  # # The Mail Transfer Agent (Postfix) receives incoming mail
  # # on TCP port 25.
  # mta:
  #   image: jeboehm/mailserver-mta:latest
  #   #env_file: "/home/admin/dev/elemento-marketplace-web/mailserver/mailserver.env"
  #   ports:
  #     - "25:25"
  #     - "587:587"
  #   # Uncomment to use SSL encrypted mail submission
  #   #  - "0.0.0.0:465:465"
  #   volumes:
  #     - data-tls:/media/tls:ro
  #     # For using external certificates uncomment the following lines
  #     # and change the path on the left side of the colon.
  #     # - /home/user/certs/mail.example.com.crt:/media/tls/mailserver.crt:ro
  #     # - /home/user/certs/mail.example.com.key:/media/tls/mailserver.key:ro
  #   networks:
  #     - net
  #   deploy:
  #     labels:
  #       - "traefik.enable=false"
  #     replicas: 1
  #     placement:
  #       max_replicas_per_node: 1
  #       constraints:
  #         - node.role == manager

  # # The Mail Delivery Agent (Dovecot) is responsible for storing
  # # incoming mail into a users mailbox and also delivers them
  # # via POP3 or IMAP4.
  # mda:
  #   image: jeboehm/mailserver-mda:latest
  #   #env_file: "/home/admin/dev/elemento-marketplace-web/mailserver/mailserver.env"
  #   ports:
  #     - "143:143"
  #     - "993:993"
  #     - "110:110"
  #     - "995:995"
  #   volumes:
  #     - data-mail:/var/vmail
  #     - data-tls:/media/tls:ro
  #     # For using external certificates uncomment the following lines
  #     # and change the path on the left side of the colon.
  #     # - /home/user/certs/mail.example.com.crt:/media/tls/mailserver.crt:ro
  #     # - /home/user/certs/mail.example.com.key:/media/tls/mailserver.key:ro
  #   networks:
  #     - net
  #   deploy:
  #     labels:
  #       - "traefik.enable=false"
  #     replicas: 1
  #     placement:
  #       max_replicas_per_node: 1
  #       constraints:
  #         - node.role == manager

  # # The admin (mailserver-admin) and webmail (roundcube) interfaces
  # # live here. Can be removed if not needed.
  # web:
  #   image: jeboehm/mailserver-web:latest
  #   #env_file: "/home/admin/dev/elemento-marketplace-web/mailserver/mailserver.env"
  #   volumes:
  #     - data-dkim:/media/dkim
  #   # For use with jwilder/nginx-proxy.
  #   # environment:
  #   #   - VIRTUAL_HOST=mail.example.com
  #   networks:
  #     - net
  #   ports:
  #     - "81:80"
  #   deploy:
  #     labels:
  #       - "traefik.enable=false"
  #     replicas: 1
  #     placement:
  #       max_replicas_per_node: 1
  #       constraints:
  #         - node.role == manager

  # # Incoming spam is (hopefully) filtered by rspamd which runs
  # # in this service.
  # filter:
  #   image: jeboehm/mailserver-filter:latest
  #   #env_file: /home/admin/dev/elemento-marketplace-web/mailserver/mailserver.env
  #   volumes:
  #     - data-filter:/var/lib/rspamd
  #     - data-dkim:/media/dkim
  #   networks:
  #     - net
  #   deploy:
  #     labels:
  #       - "traefik.enable=false"
  #     replicas: 1
  #     placement:
  #       max_replicas_per_node: 1
  #       constraints:
  #         - node.role == manager

  # # Incoming viruses or malware is detected and rejected by
  # # this service. Can be removed if FILTER_VIRUS is set to false.
  # virus:
  #   image: jeboehm/mailserver-virus:latest
  #   #env_file: /home/admin/dev/elemento-marketplace-web/mailserver/mailserver.env
  #   volumes:
  #     - data-virusdb:/var/lib/clamav
  #   networks:
  #     - net
  #   deploy:
  #     labels:
  #       - "traefik.enable=false"
  #     replicas: 1
  #     placement:
  #       max_replicas_per_node: 1
  #       constraints:
  #         - node.role == manager

  # redis:
  #   image: redis:7.2-alpine
  #   command: ["redis-server", "--appendonly", "yes"]
  #   volumes:
  #     - data-redis:/data
  #   networks:
  #     - net
  #   deploy:
  #     labels:
  #       - "traefik.enable=false"
  #     replicas: 1
  #     placement:
  #       max_replicas_per_node: 1
  #       constraints:
  #         - node.role == manager
      
  ###########################################

  traefik:
    image: traefik:v2.11
    environment:
      - GOOGLE_DOMAINS_ACCESS_TOKEN=YThLZFZsOGplRWdrZG15S04tc3hPZw==
    ports:
      - "80:80"
      #- "81:81"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/home/admin/dev/elemento-marketplace-web/traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "/home/admin/dev/elemento-marketplace-web/traefik/acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - net

volumes:
  mysql_data:
  data:
  # data-db:
  # data-dkim:
  # data-mail:
  # data-tls:
  # data-filter:
  # data-virusdb:
  # data-redis:

networks:
  net:
    external: true
    name: "net"
  