---
- name: Deploy
  hosts: localhost # TODO: Change to the server IP
  become: true
  tasks:
    - name: Update cache
      dnf:
        update_cache: yes

    - name: Install Docker
      dnf:
        name: docker-ce
        state: present
        update_cache: yes

    # - name: Clone the repository
    #   git:
    #     repo: http://github.com/Elemento-Modular-Cloud/elemento-marketplace-web
    #     dest: /mnt/shared_data/
    #     version: "main"
    #     clone: yes

    - name: Run setup.py script with flag
      script:
        cmd: /path/to/python3 ../scripts/setup.py "{{ customer }}" "{{ traefik_password }}" "{{ deploy }}"
        chdir: /mnt/shared_data/elemento-marketplace-web

    - name: Deploy Docker stack
      command: docker stack deploy --compose-file /mnt/shared_data/elemento-marketplace-web/docker-compose.yml web
