---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Info:
    - Website:
        - abbr: WE
          href: https://www.elemento.cloud
    - Github:
        - abbr: GH
          href: https://github.com/Elemento-Modular-Cloud
