---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Services:

- Admin Tools:
    - Traefik dashboard:
        icon: traefik.png
        href: https://traefik.web.elemento.cloud
        description: Overview of installed services
        widget:
            type: traefik
            url: https://traefik.web.elemento.cloud
            username: username # optional
            password: password # optional
